name: Generate README Animations

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Generate snake animation
      - name: Generate snake animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: lakipop
          outputs: |
            assets/snake.svg
            assets/snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Generate activity graph
      - name: Generate activity graph  
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: lakipop
          template: classic
          base: ""
          config_timezone: Asia/Colombo
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          filename: assets/contribution-graph.svg

      # Commit and push to main branch
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add assets/*.svg
          git diff --quiet && git diff --staged --quiet || git commit -m "Update generated SVGs [skip ci]"
          git push
